<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
    <NoWarn>$(NoWarn);MSB3277</NoWarn>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <SelfContained>true</SelfContained>
    <PublishSingleFile>true</PublishSingleFile>
    <IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>
    <EnableCompressionInSingleFile>true</EnableCompressionInSingleFile>
    <PublishTrimmed>false</PublishTrimmed>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="UIAutomationClient" HintPath="$(ProgramFiles)\dotnet\shared\Microsoft.WindowsDesktop.App\8.0.31\UIAutomationClient.dll" />
    <Reference Include="UIAutomationTypes" HintPath="$(ProgramFiles)\dotnet\shared\Microsoft.WindowsDesktop.App\8.0.31\UIAutomationTypes.dll" />
  </ItemGroup>
</Project>
